baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Neural Notes'

[params]
  wordsPerMinute = 200  # Default reading speed

# Define Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"