baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Neural Notes'

[params]
  wordsPerMinute = 200  # Default reading speed

# Define taxonomies for content organization
[taxonomies]
  tag = "tags"       # Enable tag taxonomies
  category = "categories"  # Enable category taxonomies

# Configure markdown processing
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML in markdown content